virt-s1/avocado-cloud

config/ec2_env_conf.yaml

ec2: cleanup ec2_env_conf.yaml

---

config/ec2_testcases.yaml
tests/aws/test_cloud_init.py

ec2: add test_check_cloudinit_ds_identify_found

---

config/ec2_testcases.yaml
tests/aws/test_functional_kdump.py

ec2: add test_kdump_fastboot_kexec_e which fastboot without shutdown process

---

config/openstack_testcases_cloudinit.yaml
tests/openstack/test_functional_cloudinit.py

Signed-off-by: xiachen <xiachen@redhat.com>

Adding a test case about creating VM repeatly on OpenStack

---

config/ec2_testcases.yaml
tests/aws/test_functional_lifecycle.py

ec2: add test_boot_nr_cpus to test system can boot up

---

config/openstack_testcases_cloudinit.yaml
tests/openstack/test_functional_cloudinit.py

Signed-off-by: xiachen <xiachen@redhat.com>

add two cases of cloud-utils-growpart, openstack

---

config/azure_testcases_cloudinit.yaml
tests/azure/test_functional_cloudinit.py

Add azure case: test_cloudinit_auto_resize_partition_in_mbr

---

avocado_cloud/app/aws/aws.py
tests/aws/test_cloud_init.py
tests/aws/test_functional_kdump.py
tests/aws/test_functional_lifecycle.py
tests/aws/test_functional_ltp.py
tests/aws/test_general_verification.py

ec2: cleanup cloudinit test case code

---

config/openstack_testcases_cloudinit.yaml
tests/openstack/test_functional_cloudinit.py

Signed-off-by: xiachen <xiachen@redhat.com>

add a test case of resize partition during first boot on OpenStack

---

tests/aws/test_functional_kdump.py

ec2: skip fastboot test in RHEL7

---

avocado_cloud/app/aws/aws.py
tests/aws/test_cloud_init.py
tests/aws/test_functional_kdump.py
tests/aws/test_functional_lifecycle.py
tests/aws/test_functional_ltp.py
tests/aws/test_functional_network.py
tests/aws/test_functional_storage.py
tests/aws/test_general_verification.py

ec2: clean code using aws.run_cmd()

---

config/ec2_testcases.yaml
tests/aws/test_general_verification.py

ec2: added test_check_nvme_io_timeout check

---

avocado_cloud/app/openstack/sdk.py
config/openstack_testcases.yaml
tests/openstack/test_functional_lifecycle.py

Signed-off-by: Wei Shi <wshi@redhat.com>

Refine password case for openstack

---

config/openstack_testcases_cloudinit.yaml
tests/openstack/test_functional_cloudinit.py

test_cloudinit_check_instance_data_json
test_cloudinit_login_with_password
update one case of cloud-init on openstack
test_cloudinit_login_with_publickey
Signed-off-by: Xiaoyi Chen <xiachen@xiachen.nay.csb>

add two cases of cloud-init on openstack

---

config/ec2_testcases.yaml
tests/aws/test_general_verification.py

ec2: add test_collect_insights_result

---

avocado_cloud/app/aws/aws.py
config/ec2_testcases.yaml
tests/aws/test_functional_lifecycle.py
tests/aws/test_general_verification.py

ec2: test_check_firstlaunch_time and remove test_create_vm

---

tests/aws/test_general_verification.py

ec2: fix exception when check boot time that over 1 min

---

config/azure_testcases_wala.yaml
config/azure_vm_sizes.yaml
tests/azure/test_functional_wala_storage.py

Add azure case: verify_storage_rule_gen2 and rename verify_storage_rule to verify_storage_rule_gen1

Add azure case: verify_storage_rule_gen2 and rename verify_storage_rule to verify_storage_rule_gen1

---

avocado_cloud/app/azure/sdk.py
config/azure_testcases_cloudinit.yaml
tests/azure/test_functional_cloudinit.py

Add Azure cloud-init cases
- test_cloudinit_verify_storage_rule_gen1
- test_cloudinit_verify_storage_rule_gen2

Add Azure cloud-init verify_storage_rule cases

---

tests/azure/test_functional_cloudinit.py
tests/azure/test_functional_wala_general.py

Add check waagent.conf and logrotate after upgrade

---

avocado_cloud/app/aws/sdk.py
avocado_cloud/app/setup.py
avocado_cloud/utils/utils_lib.py
config/ec2_env_conf.yaml
config/ec2_testcases.yaml
tests/aws/test_general_verification.py

ec2: add test_check_firstlaunch_compare to compare boot time with Amazon and Ubuntu

---

avocado_cloud/app/alibaba/alibaba.py
avocado_cloud/app/alibaba/sdk.py
config/alibaba_testcases.yaml
scripts/vm_check.sh
tests/alibaba/test_functional_checkup.py
tests/alibaba/test_functional_clouddisk.py
tests/alibaba/test_zcleanup.py

Code update for Alibaba

---

tests/azure/test_functional_package_preparation.py

Set repo as http://download.eng.bos.redhat.com/rhel-8/rel-eng/RHEL-8/latest-RHEL-8.x/compose/BaseOS/x86_64/os/ but not latest-RHEL-8

[Azure][package]Set repo follow the project but not the latest RHEL

---

data/azure/ignore_waagent_messages
tests/azure/test_functional_package_preparation.py

1. Add pulpcore-3.4 repo in package_preparation
2. Add a WALA ignorable log

[Azure] Add pulpcore-3.4 repo and a WALA ignorable log

---

config/ec2_testcases.yaml
tests/aws/test_general_verification.py

ec2: add test_check_journalctl_service_unknown_lvalue for bug1871139

---

avocado_cloud/app/openstack/sdk.py
config/openstack_testcases_cloudinit.yaml
tests/openstack/test_functional_cloudinit.py

test_cloudinit_check_random_password_len
test_cloudinit_create_vm_config_drive
test_cloudinit_create_vm_two_nics
test_cloudinit_create_vm_stateless_ipv6
test_cloudinit_create_vm_stateful_ipv6
Signed-off-by: Xiaoyi Chen <xiachen@xiachen.nay.csb>

Add 5 test cases of cloud-init on openstack

---

scripts/test_azure_storage_performance.sh
scripts/test_azure_storage_stability.sh

Add 2 scripts for Azure performance&stability testing

---

avocado_cloud/app/aws/sdk.py
config/ec2_env_conf.yaml

ec2: add additionalinfo option when create instance

---

avocado_cloud/app/aws/sdk.py
config/ec2_env_conf.yaml
tests/aws/test_cloud_init.py
tests/aws/test_functional_kdump.py
tests/aws/test_functional_lifecycle.py
tests/aws/test_functional_ltp.py
tests/aws/test_functional_storage.py
tests/aws/test_general_verification.py

ec2: add outposts support

---

avocado_cloud/utils/utils_lib.py
tests/aws/test_general_verification.py

ec2: update 17 cases to call os_tests

---

tests/aws/test_cloud_init.py
tests/aws/test_functional_ltp.py
tests/aws/test_functional_network.py
tests/aws/test_general_verification.py

ec2: update another 16 cases to call os_tests

---

config/ec2_testcases.yaml
tests/aws/test_general_verification.py

ec2: add test_check_lshw_mem

---

avocado_cloud/utils/utils_lib.py
tests/aws/test_functional_storage.py
tests/aws/test_general_verification.py

ec2: update test_check_virtwhat and test_check_memleaks to call os-tests

---

tests/azure/test_functional_cloudinit.py

Set subscription-manager attach --auto timeout to 120s

[Azure]Fix small issue

---

avocado_cloud/app/aws/sdk.py

ec2: add wait loop in creating new volume

---

scripts/deprovision_package.sh

[Azure] Use swapoff -a to disable all the swap in deprovisioning

---

scripts/deprovision_package.sh

[Azure] Use swapoff -a in WALA deprovisioning

---

tests/azure/test_functional_package_preparation.py

[Azure] Use nightly repo as backup if rel-eng repo doesn't exist

---

scripts/deprovision_package.sh

Avoid adding duplicated dhcp=dhclient in NetworkManager.conf

---

scripts/deprovision_package.sh

Fix dhcp=dhclient checkpoint

---

scripts/deprovision_package.sh

Add verify dhcp=dhclient in cloudinit_wala and cloudinit deprovisioning

---

config/ec2_testcases.yaml
tests/aws/test_cloud_init.py
tests/aws/test_functional_kdump.py
tests/aws/test_functional_ltp.py
tests/aws/test_functional_network.py
tests/aws/test_functional_storage.py
tests/aws/test_general_verification.py
tests/aws/test_zcleanup.py

test_check_tuned_adm_active
test_check_proc_self_status
test_check_sysfs_cpu_list
test_dracut_f_v

ec2: add 4 new cases

---

tests/azure/test_functional_package_preparation.py

[Azure]Validate compose repo url before using it

---

scripts/deprovision_package.sh

[Azure]Add dhcp=dhclient lines number check during deprovisioning

---

tests/aws/test_general_verification.py

ec2: update test_check_service to call os-tests

---

scripts/deprovision_package.sh
tests/azure/test_functional_wala_conf.py

Remove HWADDR in ifcfg-eth0 in deprovisioning

---

data/azure/ignore_waagent_messages
tests/azure/test_functional_cloudinit.py

disable htb repos to prevent 403 issue.

---

avocado_cloud/app/aws/sdk.py
config/ec2_env_conf.yaml
tests/aws/test_functional_lifecycle.py

ec2: support multiple additionalinfo when create instances

---

avocado_cloud/app/aws/aws.py
avocado_cloud/app/aws/sdk.py
tests/aws/test_functional_storage.py

ec2: handle exception if instance cannot start and no ip found

---

avocado_cloud/app/aws/sdk.py
config/ec2_env_conf.yaml
config/ec2_testcases.yaml
tests/aws/test_functional_lifecycle.py
tests/aws/test_functional_storage.py

ec2: add test_boot_mitigations and special profile support

---

avocado_cloud/app/aws/sdk.py
tests/aws/test_functional_storage.py

ec2: increase waite timeout for attached disk becomes "in-use"

---

data/azure/ignore_waagent_messages
tests/azure/test_functional_wala_conf.py
tests/azure/test_functional_wala_network.py
tests/azure/test_functional_wala_settings.py

Ignore 'UpdateGSErrors: 0' message
Remove test_functional_wala_settings.py:SettingsTest.test_extension_cleanup_if_invalid case
Fix some issues

[Azure] Fix some issues and remove test_extension_cleanup_if_invalid case

---

tests/openstack/test_functional_cloudinit.py

Update case test_cloudinit_create_vm_login_repeatedly

Cloudinit openstack

---

tests/openstack/test_functional_cloudinit.py

Signed-off-by: Xiaoyi Chen <xiachen@xiachen.nay.csb>

change command to ip addr because of no net-tool by default in rhel8.4

---

scripts/deprovision_package.sh
tests/azure/test_functional_wala_network.py

Fix deprovision_package.sh bug version and set wala change hostname inverval to 30s

---

tests/azure/test_functional_wala_network.py

Set check hostname interval to 40s

---

config/ec2_testcases.yaml
tests/aws/test_general_verification.py

ec2: add test_fork_pte for bz1908439

---

tests/azure/test_functional_package_preparation.py

Change upstream default x_version to 9 and get from project first

---

config/azure_testcases_cloudinit.yaml
data/azure/default_cloud.cfg
scripts/man-page-day.sh
tests/azure/test_functional_cloudinit.py

test_cloudinit_check_random_password_len
test_cloudinit_man_page
test_cloudinit_show_full_version
test_cloudinit_check_default_config
test_cloudinit_check_startup_time

Add 5 Azure cloud-init cases

---

tests/azure/test_functional_cloudinit.py

[Azure]Delete VM if cannot be connected in tearDown

---

tests/azure/test_functional_cloudinit.py

[Azure]Fix issue and enable test_cloudinit_verify_customized_file_in_authorizedkeysfile case

---

scripts/deprovision_package.sh
tests/azure/test_functional_package_preparation.py

[Azure]Use cloudinit_wala to deprovision in kernel testing

---

avocado_cloud/app/aws/sdk.py
avocado_cloud/utils/utils_lib.py
config/ec2_testcases.yaml
tests/aws/test_functional_network.py
tests/aws/test_functional_storage.py

ec2: added test_second_ip_hotplug for bz1642461

---

scripts/deprovision_package.sh

[Azure] Drop cloud-init services enable output in deprovisioning

---

config/azure_testcases_cloudinit.yaml

Move check_startup_time to the front

---

tests/azure/test_functional_cloudinit.py
tests/azure/test_functional_wala_network.py

Skip checking hostname -f in RHEL-9

---

tests/azure/test_functional_cloudinit.py

[Azure]Loop wait for VM bootup while getting service time

---

avocado_cloud/app/azure/sdk.py
config/azure_vm_sizes.yaml

[Azure]Change eastus2 storage to walaautolisa instead of walaautoeastus2; Support customize os_disk_size

---

avocado_cloud/app/aws/sdk.py
avocado_cloud/utils/utils_lib.py
config/ec2_env_conf.yaml
tests/aws/test_functional_lifecycle.py
tests/aws/test_functional_network.py

ec2: get availability_zone from subnet automatically

---

avocado_cloud/utils/utils_lib.py
config/ec2_testcases.yaml
tests/aws/test_functional_ltp.py
tests/aws/test_functional_storage.py
tests/aws/test_general_verification.py

ec2: added test_check_meminfo_memfree, test_check_rpm_V_efi

---

avocado_cloud/utils/utils_lib.py
config/ec2_testcases.yaml
tests/aws/test_functional_storage.py
tests/aws/test_general_verification.py

ec2: add test_check_product_id for 1938930

---

avocado_cloud/utils/utils_lib.py
config/ec2_testcases.yaml
tests/aws/test_functional_lifecycle.py
tests/aws/test_functional_storage.py
tests/aws/test_general_verification.py

test_boot_usbcore_quirks
test_boot_hpet_mmap_enabled
test_subscription_manager_auto
test_subscription_manager_config
test_check_dmidecode_outofspec
test_podman_rm_stopped
test_fsadm_resize

add 7 new cases

---

scripts/deprovision_package.sh

Remove redundant dhcp=dhclient check

---

avocado_cloud/app/aws/aws.py
avocado_cloud/utils/utils_lib.py
config/ec2_testcases.yaml
tests/aws/test_cloud_init.py
tests/aws/test_functional_lifecycle.py
tests/aws/test_functional_network.py
tests/aws/test_general_verification.py

test_check_systemd_analyze_verify_ordering_cycle for bz1932614
test_check_cloudinit_fingerprints for bz1957532
test_ethtool_S_xdp for 1908542
test_check_cloudinit_cfg_no_wheel for bz1549638

ec2: added 4 new testcases

---

scripts/deprovision_package.sh

Support old non-cloudinit images in deprovision_package kernel

---

avocado_cloud/app/ibmcloud/__init__.py
avocado_cloud/app/ibmcloud/sdk.py
avocado_cloud/app/setup.py
avocado_cloud/utils/utils_ibmcloud.py
config/ibmcloud_common.yaml
config/ibmcloud_test.yaml
config/ibmcloud_testcases_cloudinit.yaml
tests/ibmcloud/test_functional_cloudinit.py

IBM Cloud test cases

---

data/azure/default_cloud.cfg

Change default_cloud.cfg to ssh_genkeytypes:  ['rsa', 'ecdsa', 'ed25519']

---

tests/azure/test_functional_package_preparation.py

[Azure] Reinstall rhui from MS repo

---

tests/azure/test_functional_cloudinit.py

[Azure]Fix cannot get boot device issue

---

config/azure_testcases.yaml
config/azure_testcases_cloudinit.yaml
data/azure/ignore_cloudinit_messages
tests/azure/test_functional_cloudinit.py

[Azure]Remove 2 subscription cases and do not auto-attach

---

tests/azure/test_functional_cloudinit.py

[Azure] Fix cloud-init cfg and users cleanup failed issue

---

tests/azure/test_functional_wala_conf.py
tests/azure/test_functional_wala_function.py
tests/azure/test_functional_wala_general.py
tests/azure/test_functional_wala_lifecycle.py
tests/azure/test_functional_wala_network.py

Fix wala cases issues for v2.3.0.2 and save waagent.log in sshkey_log in case

---

config/ec2_testcases.yaml
tests/aws/test_functional_network.py
tests/aws/test_general_verification.py

- add test_check_systemd_analyze_verify_obsolete for bz1974108
- add test_check_systemd_analyze_verify_deprecated_unsafe for bz1974184
- add test_persistent_route for bz1971527

ec2: added 3 new cases

---

tests/azure/test_functional_wala_conf.py

Fix get temporary device name function

---

config/openstack_testcases_cloudinit.yaml
tests/openstack/test_functional_cloudinit.py

Add a test case for openstack, checking /etc/resolv.conf after reboot

---

avocado_cloud/app/openstack/sdk.py
config/openstack_testcases_cloudinit.yaml
tests/openstack/test_functional_cloudinit.py

Add a case of checking runcmd for cloud-init on openstack, and update the case of checking random password length

Add a case of checking runcmd for cloud-init on openstack,

---

config/openstack_testcases_cloudinit.yaml
tests/openstack/test_functional_cloudinit.py

Add a case for cloud-init on openstack, checking cloud-init full version
Update a case for cloud-init on openstack, checking random password not logged 

Add a case for cloud-init on openstack, checking cloud-init full version

---

config/openstack.yaml
config/openstack_testcases_cloudinit.yaml
tests/openstack/test_functional_cloudinit.py

Add a case of cloud-init on openstack, subscription-manager

---

config/openstack_cloudinit.yaml
tests/openstack/test_functional_cloudinit.py

Fix stage account issue, cloud-init on openstack

---

avocado_cloud/utils/utils_lib.py
config/ec2_testcases.yaml
tests/aws/test_general_verification.py

ec2: added 8 new os-tests cases to ci run

---

tests/azure/test_functional_cloudinit.py

Changed from cloud-init-21.1-3.el8 and cloud-init-21.1-4.el9.

[Azure]cloud-init random password will only be shown on serial console but not log

---

config/openstack.yaml
tests/openstack/test_functional_cloudinit.py

test_cloudinit_check_resolv_conf_reboot
test_cloudinit_show_full_version

Update 2 cases of cloud-init on openstack

---

config/openstack_testcases_cloudinit.yaml
tests/azure/test_functional_cloudinit.py
tests/openstack/test_functional_cloudinit.py

test_cloudinit_verify_rh_subscription_enablerepo_disablerepo
test_cloudinit_auto_install_package_with_subscription_manager

Add/update cloud-init cases

---

config/openstack_testcases_cloudinit.yaml
tests/openstack/test_functional_cloudinit.py

Add two cases for openstack cloud-init:
test_cloudinit_boot_time
test_cloudinit_reboot_time

Add two cases for openstack cloud-init

---

config/openstack_testcases_cloudinit.yaml
tests/openstack/test_functional_cloudinit.py

Add a case test_check_hostkey_permissions

---

tests/openstack/test_functional_cloudinit.py

Update case test_cloudinit_verify_customized_file_in_authorizedkeysfile

---

scripts/deprovision_package.sh

[Azure] disable resource disk format while deprovisioning VM with cloudinit_wala

---

config/openstack_testcases_cloudinit.yaml
tests/openstack/test_functional_cloudinit.py

Added one case of test_cloudinit_datasource_openstack for openstack cloud-init

Add one case for openstack cloud-init

---

avocado_cloud/app/nutanix/__init__.py
avocado_cloud/app/nutanix/nutanix.py
avocado_cloud/app/nutanix/sdk.py
avocado_cloud/app/setup.py
avocado_cloud/utils/ssh_key.py
config/nutanix.yaml
config/nutanix_flavors.yaml
config/nutanix_testcases.yaml
config/test_nutanix.yaml
tests/nutanix/test_functional_lifecycle.py

Signed-off-by: Wei Shi <wshi@redhat.com>

Add nutanix support with basic lifecycle testcases

---

tests/azure/test_functional_cloudinit.py

Hello Yuxin, please kindly review the fixes proposed and let me know any modifications needed. Thank you!

Fixed 2 test case failures in Azure

---

tests/azure/test_functional_cloudinit.py

Remove 'utf-8' in str since it's not support in python2

---

config/openstack_testcases_cloudinit.yaml
tests/azure/test_functional_cloudinit.py
tests/openstack/test_functional_cloudinit.py

Update 1 case for Azure cloud-init
Add 1 case for OpenStack cloud-init

Update cloud-init case on Azure and OpenStack

---

tests/azure/test_functional_cloudinit.py

[Azure]Correct test_cloudinit_provision_gen2_vm introduction

---

avocado_cloud/app/azure/sdk.py
config/azure_testcases_cloudinit.yaml
tests/azure/test_functional_cloudinit.py

[Azure]Add 2 new cases:
test_cloudinit_save_and_handle_userdata_script
test_cloudinit_save_and_handle_userdata_cloudinit_config

[Azure]Add 2 userdata cases

---

tests/openstack/test_functional_cloudinit.py

_check_cloudinit_services_isactive
_check_cloudinit_done_and_service_isactive
Modify 7 cases
test_cloudinit_check_services_status
test_cloudinit_login_with_password
test_cloudinit_create_vm_config_drive
test_cloudinit_create_vm_two_nics
test_cloudinit_create_vm_stateless_ipv6
test_cloudinit_create_vm_stateful_ipv6
test_cloudinit_auto_install_package_with_subscription_manager

Add two cloud-init openstack common functions

---

tests/openstack/test_functional_cloudinit.py

Checking IPv6 route prefix in case test_cloudinit_check_config_ipv6

---

scripts/deprovision_package.sh

[Azure]Setup WALA config for old WALA version in deprovision_package.sh

---

tests/azure/test_functional_cloudinit.py

Update Azure cloud-init case test_cloudinit_show_full_version

---

data/azure/ignore_cloudinit_messages

Add ignorable cloud-init.log failed message

---

tests/openstack/test_functional_cloudinit.py

Update case test_cloudinit_boot_time on openstack

---

tests/azure/test_functional_package_preparation.py

[Azure]Change rpm -e timeout

---

tests/azure/test_functional_wala_conf.py
tests/azure/test_functional_wala_general.py

1. Create gen2 image in Azure wala gen2 case
2. Fix cannot delete user when deprovision VM

[Azure]Fix 2 WALA issues

---

tests/openstack/test_functional_cloudinit.py

Update openstack case test_cloudinit_create_vm_login_repeatedly

---

tests/azure/test_functional_wala_conf.py
tests/azure/test_functional_wala_general.py
tests/azure/test_functional_wala_storage.py

[Azure]Fix issues in WALA testing

---

config/openstack_testcases_cloudinit.yaml
tests/openstack/test_functional_cloudinit.py

because it caused case failure

Remove self._output_cloudinit_log from serveral cases 

---

scripts/deprovision_package.sh

Create ifcfg-eth0 in deprovision_wala to workaround BZ#2092002

---

config/azure_vm_sizes.yaml
tests/azure/test_functional_wala_conf.py
tests/azure/test_functional_wala_general.py
tests/azure/test_functional_wala_network.py
tests/azure/test_functional_wala_settings.py
tests/azure/test_functional_wala_storage.py

[Azure]Fix WALA issues

---

tests/azure/test_functional_wala_conf.py

[Azure] Delete VM if not available

---

data/alibaba/rogue.el9.lst
data/alibaba/vulnerabilities.el8.lst
data/alibaba/vulnerabilities.el9.lst
tests/alibaba/test_functional_checkup.py

1. Add whitelist for RHEL8.6 and RHEL9.0 test
2. Correct the product certificate file on RHEL9
3. Modify the boot time maximum

Some minor changes for RHEL8.6 and RHEL9.0 images

---

tests/azure/test_functional_wala_conf.py

[Azure]Remove DHCP_HOSTNAME check in test_monitor_hostname

---

tests/azure/test_functional_wala_general.py

[Azure] Make upgrade_downgrade script stronger

---

avocado_cloud/app/openstack/sdk.py
config/openstack_testcases_cloudinit.yaml
tests/openstack/test_functional_cloudinit.py

add two cases
1. test_cloudinit_package_upgrade
2. test_cloudinit_os_upgrade
set VM setup timeout to 600s

cloud-init upgrade cases on openstack

---

tests/openstack/test_functional_cloudinit.py

Update case test_cloudutils_growpart_resize_partition_first_boot

---

avocado_cloud/app/ibmcloud/sdk.py
config/ibmcloud_common.yaml

Update ibmcloud sdk for adjusting timeout and storage-pool.

---

tests/openstack/test_functional_cloudinit.py

Modify user-data for default test cloud-init on openstack.

---

avocado_cloud/utils/utils_azure.py
config/azure_testcases_wala.yaml
tests/azure/test_functional_wala_conf.py
tests/azure/test_functional_wala_function.py
tests/azure/test_functional_wala_general.py
tests/azure/test_functional_wala_network.py

Automate 8 cases

---

config/azure_testcases_wala.yaml
tests/azure/test_functional_wala_conf.py
tests/azure/test_functional_wala_general.py
tests/azure/test_functional_wala_lifecycle.py
tests/azure/test_functional_wala_network.py

Add 8 cases:
+    test_functional_wala_general.py:GeneralTest.test_check_waagent_network_setup_service
+    test_functional_wala_network.py:NetworkTest.test_verify_dhclient_not_in_waagent_cgroup
+    test_functional_wala_conf.py:WALAConfTest.test_enable_fips
+    test_functional_wala_conf.py:WALAConfTest.test_logs_collect
+    test_functional_wala_conf.py:WALAConfTest.test_enable_firewall
+    test_functional_wala_conf.py:WALAConfTest.test_monitor_dhcp_client_restart_period
+    test_functional_wala_conf.py:WALAConfTest.test_remove_persistent_net_rules_period
+    test_functional_wala_lifecycle.py:LifeCycleTest.test_create_vm_without_deprovision

Add 8 cases

---

tests/azure/test_functional_wala_conf.py
tests/azure/test_functional_wala_general.py

[Azure] Collect more logs when case is failed

---

tests/openstack/test_functional_cloudinit.py

Add testcase name to tag

---

tests/openstack/test_functional_cloudinit.py

Cancel the cases which are not support CentOS

---

tests/openstack/test_functional_cloudinit.py

Fix issue of CentOS

---

config/azure_testcases_cloudinit.yaml
tests/azure/test_functional_cloudinit.py

Adding 1 cloud-init case on Azure: test_cloudinit_update_network_every_boot

Add one Azure cloud-init case

---

config/azure_testcases_wala.yaml
tests/azure/test_functional_package_preparation.py
tests/azure/test_functional_wala_conf.py
tests/azure/test_functional_wala_general.py

1. Add new case: test_change_python_version
2. Don't enable fips in wala conf in fips case

Add new case: test_change_python_version and fix fips case

---

data/alibaba/rogue.el8.lst
scripts/nm-cloud-setup.sh
tests/alibaba/test_functional_checkup.py

1.Modify the virt-what test case for ARM image
2.Increase the timeout for kernel fastboot test
3.Add white list for RHEL8.7 ARM image
4.Add nm-cloud-setup.sh for previous commit

Some minor changes for alibaba test

---

data/alibaba/cmdline_params.el8.arm64.lst
data/alibaba/cmdline_params.el9.arm64.lst
tests/alibaba/test_functional_checkup.py

1.Add new test case to check the mode of /dev/null file
2.Modify the boot parameters content for arm images

Add new test case to check the mode of /dev/null file and modify the boot parameters content for arm images

---

tests/azure/test_functional_cloudinit.py

Update 1 case: test_cloudinit_check_networkmanager_dispatcher

Update cloud-init case per new change in 23.4

---

avocado_cloud/app/alibaba/alibaba.py
avocado_cloud/app/alibaba/sdk.py
data/alibaba/file_cmp.el8.5/%etc%cloud%cloud.cfg
data/alibaba/file_cmp.el8/%etc%cloud%cloud.cfg
data/alibaba/file_cmp.el9/%etc%cloud%cloud.cfg
data/alibaba/journalctl.el8.lst
data/alibaba/journalctl.el9.lst
data/alibaba/rogue.el8.lst
data/alibaba/rogue.el9.lst
data/alibaba/rpm_va.el8.lst
data/alibaba/rpm_va.el9.lst
tests/alibaba/test_functional_lifecycle.py
tests/alibaba/test_functional_network.py

1.Update cloud.cfg for Alibaba testing
2.Remove the nm-cloud-setup configuration since the services are enabled inside the image from RHEL8.9/9.3 
3.Some experimental codes about RunInstances sdk
4.Some other mixed changes

Some updates for Alibaba testing

---

tests/azure/test_functional_package_preparation.py

The rhel-10 repo is RHEL-10-Public-Beta currently, so update it to RHEL-10-Public-Beta

Update rhel-10 repo to RHEL-10-Public-Beta

---

avocado_cloud/app/alibaba/alibaba.py
avocado_cloud/app/alibaba/sdk.py
data/alibaba/file_cmp.el8.5/%etc%cloud%cloud.cfg
data/alibaba/file_cmp.el8/%etc%cloud%cloud.cfg
data/alibaba/file_cmp.el9/%etc%cloud%cloud.cfg
data/alibaba/rogue.el8.lst
data/alibaba/vulnerabilities.el8.lst
data/alibaba/vulnerabilities.el9.lst
tests/alibaba/test_functional_checkup.py
tests/alibaba/test_functional_lifecycle.py

1.Change the API when creating instance
2.Update cloud.cfg
3.Some other minor changes

Modify the API when creating instance and some other minor changes

---

tests/azure/test_functional_wala_function.py
tests/azure/test_functional_wala_general.py
tests/azure/test_functional_wala_network.py

* Fix get packages inside VM issue
* Skip waagent -collect-logs in RHEL-9+ and WALA-2.9.1.1+

Fix install/upgrade cases issues

---

tests/azure/test_functional_cloudinit.py

Update case test_cloudinit_auto_extend_root_partition_and_filesystem as cloud-utils removes dependency gdisk

Update 1 cloud-init case per rhel-10 latest status

---

tests/azure/test_functional_cloudinit.py

it does not support 24.1+ NM renderer

Update case test_cloudinit_update_network_every_boot
