avocado_cloud/app/aws/sdk.py

Not all instance types support this option, so continue to get console
log with latest disabled if exception hit.

ec2: try get console log with latest enabled

---

tests/aws/test_functional_kdump.py

More arm bases instances released, eg. c6g and r6g. So cancel such case
according to cpu types instead of instance type name.

ec2: skip kdump saving core test in arm instance according to cpu type

---

avocado_cloud/app/azure/sdk.py
tests/azure/test_functional_cloudinit.py

Add AzureImage class in azure/sdk.py. 
Create image before creating VM while running gen2 case to follow the MSFT recommended way in azure cloud-init test.

Add AzureImage class. Create image in gen2 test in Azure cloud-init test

---

avocado_cloud/app/setup.py
config/azure_testcases_cloudinit.yaml
tests/azure/test_functional_cloudinit.py

Add Azure cloud-init cases:
+    test_functional_cloudinit.py:CloudinitTest.test_cloudinit_verify_multiple_files_in_authorizedkeysfile
+    test_functional_cloudinit.py:CloudinitTest.test_cloudinit_verify_customized_file_in_authorizedkeysfile (skip now)
+    test_functional_cloudinit.py:CloudinitTest.test_cloudinit_remove_cache_and_reboot_password

Add 3 Azure cloud-init cases

---

avocado_cloud/app/openstack/sdk.py
config/openstack_testcases_cloudinit.yaml
tests/openstack/test_functional_cloudinit.py

1. Add one case 'test_cloudinit_check_config_ipv6' on openstack
2. Change the condition of getting foating_ip in openstack sdk
3. Delete VM created by case 'test_cloudinit_login_with_password' in tearDown
Signed-off-by: Xiaoyi Chen <xiachen@xiachen.nay.csb>

Add one case 'test_cloudinit_check_config_ipv6' on openstack

---

config/azure_testcases_cloudinit.yaml
tests/azure/test_functional_cloudinit.py

+    test_functional_cloudinit.py:CloudinitTest.test_cloudinit_auto_register_with_subscription_manager
+    test_functional_cloudinit.py:CloudinitTest.test_cloudinit_auto_install_package_with_subscription_manager
+    test_functional_cloudinit.py:CloudinitTest.test_cloudinit_verify_rh_subscription_enablerepo_disablerepo
+    test_functional_cloudinit.py:CloudinitTest.test_cloudinit_enable_swap_in_temporary_disk
+    test_functional_cloudinit.py:CloudinitTest.test_cloudinit_swapon_with_xfs_filesystem
+    test_functional_cloudinit.py:CloudinitTest.test_cloudinit_chpasswd_with_hashed_passwords
+    test_functional_cloudinit.py:CloudinitTest.test_cloudinit_runcmd_module_execute_command
+    test_functional_cloudinit.py:CloudinitTest.test_cloudinit_check_ds_identity_path
Signed-off-by: Yuxin …

Add 8 Azure cloud-init cases

---

scripts/deprovision_package.sh
tests/azure/test_functional_cloudinit.py

1. Remove cloud-init instead of disable it in deprovision_package.sh wala part to prevent the cloud-init impact to waagent provisioning
2. Fix issue in test_cloudinit_chpasswd_with_hashed_passwords and test_cloudinit_save_and_handle_customdata_cloudinit_config

[Azure]Remove cloud-init in deprovisioning and fix issues

---

data/azure/ignore_cloudinit_messages
tests/azure/test_functional_cloudinit.py

- Ignore "finish: azure-ds/load_azure_ds_dir: FAIL: load_azure_ds_dir" in _check_cloudinit_log
- Ignore "WARNING" in _verify_rh_subscription
- Use "subscription-manager attach --auto" to auto attach pool manually

Add ignorable fail logs in Azure and fix a issue

---

data/azure/ignore_cloudinit_messages

Add ignorable cloud-init error log:
handlers.py[DEBUG]: diagnostic: diagnostic message: dhclient error stream: Internet Systems Consortium DHCP Client

[Azure] Add ignorable cloud-init error log

---

tests/azure/test_functional_cloudinit.py

In RHEL-8:
if LooseVersion(version) < LooseVersion("19.4"):
ds_identify = "/usr/lib/cloud-init/ds-identify"
else:
ds_identify = "/usr/libexec/cloud-init/ds-identify"
In RHEL-7:
ds_identify = "/usr/lib/cloud-init/ds-identify"

[Azure]Fix ds-identity file path

---

tests/azure/test_functional_package_preparation.py
tests/azure/test_functional_wala_network.py

WALA package doesn't use pulpcore repo to prevent the RHEL-8.0 systemd update issue
Increase WALA network hostname cases wait time to 30s

[Azure]WALA package doesn't use pulpcore repo

---

tests/azure/test_functional_wala_function.py

Stop NetworkManager before waagent deprovision or it will regenerate resolv.conf in RHEL-8.4

---

config/azure_testcases_cloudinit.yaml
tests/azure/test_functional_cloudinit.py

+    test_functional_cloudinit.py:CloudinitTest.test_cloudinit_lang_is_not_en_us_utf8
+    test_functional_cloudinit.py:CloudinitTest.test_cloudinit_mount_with_noexec_option
+    test_functional_cloudinit.py:CloudinitTest.test_cloudinit_no_networkmanager

[Azure] Add 3 cloud-init cases

---

tests/azure/test_functional_cloudinit.py

Since RHEL-9 cannot get domain name with hostname -f

[Azure] Do not verify domain name in FQDN

---

README.md

Use the project's GitHub URL for the "git clone" instruction.
Signed-off-by: Cleber Rosa <crosa@redhat.com>

README.md: use the public GitHub URL for the repository

---

config/openstack_testcases_cloudinit.yaml
tests/openstack/test_functional_cloudinit.py

Update two cloud-init cases on openstack:    
test_cloudinit_verify_customized_file_in_authorizedkeysfile
test_cloudinit_verify_multiple_files_in_authorizedkeysfile

Update two cases per BZs

---

tests/azure/test_functional_cloudinit.py

Workaround: remove '\n' from cloud-init --version output in cloud-init-21.1-8.el9.noarch.rpm

---

config/openstack_testcases_cloudinit.yaml
tests/azure/test_functional_cloudinit.py
tests/openstack/test_functional_cloudinit.py

test_check_cloudinit_fingerprints
test_cloudinit_lang_is_not_en_us_utf8
Update polarion id and case name for 7 cloud-init cases on Azure.

Add two cloud-init cases for openstack

---

avocado_cloud/app/aws/sdk.py
config/ec2_testcases.yaml
tests/aws/test_functional_ltp.py
tests/aws/test_functional_network.py
tests/aws/test_general_verification.py

-start preview instances if addtionalinfo is provided
-rename test_check_sys_modules_parameters to test_check_sys_modules_parameters_readable
-rename test_ltp_quickhit to test_ltp_smoketest following ltp upstream

sync with several fixes

---

avocado_cloud/app/alibaba/sdk.py
tests/alibaba/test_functional_clouddisk.py

```
JOB ID     : d35b1a1e3141f389edc8dbd3e4b6c5c9ef741424
JOB LOG    : /root/avocado/job-results/job-2022-03-21T04.53-d35b1a1/job.log
(1/3) /app/tests/alibaba/test_functional_clouddisk.py:CloudDiskTest.test_local_disks;Cloud-Credential-Disk-ecs.i2.2xlarge-Image-NIC-VSwitch-SecurityGroup-password-username-VM-8c89:  PASS (3.47 s)
(2/3) /app/tests/alibaba/test_functional_clouddisk.py:CloudDiskTest.test_online_attach_detach_cloud_disks;Cloud-Credential-Disk-ecs.i2.2xlarge-Image-NIC-VSwitch-SecurityGroup-password-username-VM-8c89:  PASS (208.95 s)
(3/3) /app/tests/alibaba/test_functional_clouddisk.py:CloudDiskTest.test_offline_attach_detach_cloud_disks;Cloud-Credential-Disk-ecs.i2.2xlarge-Image-NIC-VSwitch-SecurityGroup-password-username-VM-8c89:  PASS (408.24 s)
RESULTS    : PASS 3 | ERROR 0 …
```

Enhance local disk and cloud disk test cases for Aliyun

---

data/azure/default_cloud_90.cfg
tests/azure/test_functional_cloudinit.py

1. For test_cloudinit_check_random_password_len, extend sleep time to make sure the serial console refresh finished.
2. For test_cloudinit_check_default_config, The default cloud.cfg is different in rhel-9.0 as bz 1998445, fix script to diff rhel-9.0 and other rhel-versions.
3. For test_cloudinit_dhclient_hook_disable_cloudinit, changing redeploy VM to cleanup/restart VM

Fix some issues for azure cloud-init

---

tests/azure/test_functional_cloudinit.py
tests/openstack/test_functional_cloudinit.py

Fix the issue that cloud-init status is running
_check_cloudinit_done_and_service_isactive
test_cloudinit_login_with_password
test_cloudinit_create_vm_config_drive
test_cloudinit_create_vm_two_nics
test_cloudinit_create_vm_stateless_ipv6
test_cloudinit_create_vm_stateful_ipv6
test_cloudinit_auto_install_package_with_subscription_manager
Fix azure case 'ms' issue
test_cloudinit_check_startup_time

Update cloud-init cases about status of running or done

---

tests/openstack/test_functional_cloudinit.py

In rhel-guest-image, /etc/ssh/sshd_config default value is PasswordAuthentication yes
To trigger sshd service restart in openstack cloud-init case, we should set ssh_pwauth: 0

Set ssh_pwauth: 0 to trigger sshd service restart in openstack cloud-init

---

avocado_cloud/app/alibaba/sdk.py
data/alibaba/cmdline_params.el9.lst
tests/alibaba/test_functional_network.py

1. Add checkpoints for kernel parameters on RHEL9
2. Modify the previous test case(test_assign_unassign_secondary_private_ips)

Add checkpoints for kernel parameters on RHEL9 and modify test_assign_unassign_secondary_private_ips test case

---

tests/azure/test_functional_cloudinit.py

Fix two azure cloud-init cases per the change of /etc/cloud/cloud.cfg:
test_cloudinit_regenerate_sshd_keypairs
test_cloudinit_check_default_config

Fix two azure cloud-init cases per the /etc/cloud/cloud.cfg change

---

avocado_cloud/app/alibaba/sdk.py
data/alibaba/rogue.el8.lst
data/alibaba/rogue.el9.lst
data/alibaba/rpm_va.el8.lst
data/alibaba/rpm_va.el9.lst
data/alibaba/vulnerabilities.el8.lst
data/alibaba/vulnerabilities.el9.lst
tests/alibaba/test_functional_checkup.py

1. Add whitelist for RHEL8.6 arm image
2. Check product certificate for RHEL8.6 arm image
3. Get the arch info from flavor configure file
4. Add whitelist for RHEL9.0 image since the podman rpm is required by CCSP

Some changes for RHEL8.6 arm image and RHEL9.0 image

---

data/alibaba/cmdline_params.lst
data/alibaba/journalctl.el8.lst
data/alibaba/journalctl.el9.lst
data/alibaba/rpm_va.el8.lst
data/alibaba/rpm_va.el9.lst
data/alibaba/vulnerabilities.el8.lst
data/alibaba/vulnerabilities.el9.lst
tests/alibaba/test_functional_checkup.py

1. Add whitelist for RHEL8.7 and RHEL9.1 images
2. Modify virt-what test case since the latest virt-what supports Alibaba Cloud Linux

Add whitelist for RHEL8.7 & RHEL9.1 images and Modify virt-what test case

---

tests/azure/test_functional_cloudinit.py
tests/openstack/test_functional_cloudinit.py

1. test_cloudinit_save_and_handle_customdata_cloudinit_config
Skipped 3 modules in 23.1.1, so only run 3 modules.     
There is log likes "Skipping modules 'yum-add-repo,disable-ec2-metadata,runcmd' because no applicable config is provided"
2. test_cloudinit_save_and_handle_userdata_cloudinit_config
Same as above 1.
3. test_cloudinit_check_ds_identity_path
Check "ds-identify rc=0" instead of "ds-identify _RET=found", as the log "ds-identify _RET=found" is deleted in 23.1.1

Fix 3 test cases per changes in rebase 23.1.1

---

tests/azure/test_functional_cloudinit.py

Update the case: test_cloudinit_swapon_with_xfs_filesystem

Fix one cloud-init case on azure

---

tests/openstack/test_functional_cloudinit.py

Error: Cloud config schema errors: ssh_pwauth: 0 is not valid under any of the given schemas
22.3 onwards  Use of non-boolean values for this field is deprecated.
so fix it to boolean value

Update invalid user-data for cloud-init openstack
